# Generated by Django 3.0 on 2019-12-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sub_tasks_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
