# Generated by Django 3.0.1 on 2020-01-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], default='NEW', max_length=10),
        ),
    ]
