# Generated by Django 3.0.1 on 2020-01-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200113_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_tasks_count',
        ),
    ]
