# Generated by Django 3.0.1 on 2020-01-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='body',
        ),
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], default='NEW', max_length=10, null=True),
        ),
    ]
